development:
  adapter: postgresql
  database: hannah_kunce_development
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: hannah_kunce_production
  pool: 5
  timeout: 5000
  host: localhost
